# 0. Setup Libraries

In [ ]:
! pip install astropy

# 1. Setup folders

In [ ]:
import os

In [ ]:
paths = {
    'RAW_DATA_PATH' : os.path.join('workspace', 'raw_data'),
    'IMAGES_PATH' : os.path.join('workspace', 'images', 'all'),
    'IMAGES_ANNOTATED_PATH' : os.path.join('workspace', 'images', 'all','annotated'),
    'TRAIN_PATH' : os.path.join('workspace', 'images', 'train'),
    'EVAL_PATH' : os.path.join('workspace', 'images', 'eval'),
    'TEST_PATH' : os.path.join('workspace', 'images', 'test')
 }

In [ ]:
for path in paths.values():
    if not os.path.exists(path):
        if os.name == 'posix':
            !mkdir -p {path}
        if os.name == 'nt':
            !mkdir {path}

# 1. Move or download the h5 file in the correct folder

TODO: Transfer images to be converted in "workspace/raw_data" folder

# 2. Convert h5 file to jpg images (1st version)

In [ ]:
import os
import h5py
import numpy as np
from keras import utils
from matplotlib import pyplot as plt
import time

#for filename in os.listdir(os.path.join("workspace","raw_data")):
#    if filename.endswith(".h5"):
#        with h5py.File(os.path.join("workspace","raw_data",filename), 'r') as F:
#            images = np.array(F['images'])
#            labels = np.array(F['ans'])
#            print(images)
#            print(labels)
            # convert the labels to categorical 10 classes
#            labels = utils.to_categorical(labels, 10)

            # To convert to desirable type
#            labels = labels.astype(np.float32)
#            images = images.astype(np.float32)
#            print(images)
#            print(labels)
#            for image in images:
#                plt.imshow(image, interpolation='nearest')
#                plt.show()
#                time.sleep(5000)

# 2. Convert h5 file to jpg images using astroNN (2nd version)

In [4]:
! pip install astroNN

In [19]:
from astroNN.datasets import load_galaxy10
from keras import utils
import numpy as np
import os
from PIL import Image

# To load images and labels (will download automatically at the first time)
# First time downloading location will be ~/.astroNN/datasets/
images, labels = load_galaxy10()

for label in np.unique(labels):
     IMAGES_PATH = os.path.join('workspace', 'images', 'all', str(label))
     !mkdir -p {IMAGES_PATH}
print("Folders created...")

print("Saving images in the correct folder...")
print(images.size)
print(labels.size)
for i in range(0,labels.size):
    image = images[i]
    label = labels[i]
    #plt.imshow(image, interpolation='nearest')
    im = Image.fromarray(image)
    im.save(os.path.join('workspace', 'images', 'all', str(label),str(i)+".jpg"))
    if i% 100 == 0:
        print(i)

/Users/francoterranova/.astroNN/datasets/Galaxy10.h5 was found!
Folders created...
Saving images in the correct folder...
311155155
21785
0
100
200
300
400
500
600
700
800
900
1000
1100
1200
1300
1400
1500
1600
1700
1800
1900
2000
2100
2200
2300
2400
2500
2600
2700
2800
2900
3000
3100
3200
3300
3400
3500
3600
3700
3800
3900
4000
4100
4200
4300
4400
4500
4600
4700
4800
4900
5000
5100
5200
5300
5400
5500
5600
5700
5800
5900
6000
6100
6200
6300
6400
6500
6600
6700
6800
6900
7000
7100
7200
7300
7400
7500
7600
7700
7800
7900
8000
8100
8200
8300
8400
8500
8600
8700
8800
8900
9000
9100
9200
9300
9400
9500
9600
9700
9800
9900
10000
10100
10200
10300
10400
10500
10600
10700
10800
10900
11000
11100
11200
11300
11400
11500
11600
11700
11800
11900
12000
12100
12200
12300
12400
12500
12600
12700
12800
12900
13000
13100
13200
13300
13400
13500
13600
13700
13800
13900
14000
14100
14200
14300
14400
14500
14600
14700
14800
14900
15000
15100
15200
15300
15400
15500
15600
15700
15800
15900
16000
16100
16

In [21]:
# To convert the labels to categorical 10 classes
labels = utils.to_categorical(labels, 10)

# To convert to desirable type
labels = labels.astype(np.float32)
images = images.astype(np.float32)

[[[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 ...

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]]

 [[1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [0. 1. 0. ... 0. 0. 0.]
  ...
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]
  [1. 0. 0. ... 0. 0. 0.]]]


# 2. Label images using LabelImg (optional)

In [ ]:
! pip install labelImg

TODO: Label images in the workspace/raw_data folder

# 3. Move annotated images in a predefined folder for splitting

In [ ]:
from moveAnnotations import moveAnnotations
moveAnnotations()

# 3.a. Split data with Holdout

In [ ]:
from sklearn.model_selection import train_test_split
import pandas as pd
import shutil
import os

eval_size = 0

# remove all files already present for an old holdout method execution
for file in os.listdir(paths["TRAIN_PATH"]):
    if file != ".DS_Store":
        os.remove(os.path.join(paths["TRAIN_PATH"], file))
for file in os.listdir(paths["TEST_PATH"]):
    if file != ".DS_Store":
        os.remove(os.path.join(paths["TEST_PATH"], file))
for file in os.listdir(paths["EVAL_PATH"]):
    if file != ".DS_Store":
        os.remove(os.path.join(paths["EVAL_PATH"], file))

# collect all annotated images except those of user B and K
df = pd.DataFrame()
for image in os.listdir(paths["IMAGES_ANNOTATED_PATH"]):
    new_row = { 'Path': image }
    df = df.append(new_row, ignore_index=True)

# split in the training set (90%) and a validation set (10%)
X_train, X_eval, _, _ = train_test_split(df, df, test_size=0.1, shuffle=True)

# split the training images into the final training set (80%) and add the rest (20%) to the test set
X_train, X_test, _, _ = train_test_split(X_train, X_train, test_size=0.8, shuffle=True)

print("Train size: " + str(len(X_train)))
print("Test size: " + str(len(X_test)))
print("Eval size: " + str(eval_size))

for _, row in X_eval.iterrows():
    shutil.copy(os.path.join(paths["IMAGES_ANNOTATED_PATH"],row['Path']),
                os.path.join(paths["EVAL_PATH"],row['Path']))
    shutil.copy(os.path.join(paths["IMAGES_ANNOTATED_PATH"],row['Path'].split(".jpg")[0]+".xml"),
                os.path.join(paths["EVAL_PATH"],row['Path'].split(".jpg")[0]+".xml"))

for _, row in X_eval.iterrows():
    shutil.copy(os.path.join(paths["IMAGES_ANNOTATED_PATH"],row['Path']),
                os.path.join(paths["EVAL_PATH"],row['Path']))
    shutil.copy(os.path.join(paths["IMAGES_ANNOTATED_PATH"],row['Path'].split(".jpg")[0]+".xml"),
                os.path.join(paths["EVAL_PATH"],row['Path'].split(".jpg")[0]+".xml"))

for _, row in X_test.iterrows():
    shutil.copy(os.path.join(paths["IMAGES_ANNOTATED_PATH"],row['Path']),
                os.path.join(paths["TEST_PATH"],row['Path']))
    shutil.copy(os.path.join(paths["IMAGES_ANNOTATED_PATH"],row['Path'].split(".jpg")[0]+".xml"),
                os.path.join(paths["TEST_PATH"],row['Path'].split(".jpg")[0]+".xml"))